#!/bin/bash

# 1. Remove Loveable metadata files
echo "🧹 Removing Loveable metadata..."
rm -rf .loveable .loveable-settings.json

# 2. Rename folders (customize if needed)
if [ -d "src/sections/loveable" ]; then
  echo "📁 Renaming src/sections/loveable → src/sections/home"
  mv src/sections/loveable src/sections/home
fi

# 3. Replace import paths and references from 'loveable' to 'home'
echo "🔍 Rewriting import paths..."
find src -type f \( -name "*.ts" -o -name "*.tsx" \) -exec sed -i '' 's@/sections/loveable@/sections/home@g' {} +

# 4. Remove comments like 'Generated by Loveable.dev'
echo "📝 Removing Loveable comments..."
find src -type f \( -name "*.ts" -o -name "*.tsx" \) -exec sed -i '' '/Loveable\.dev/d' {} +

# 5. Search and list remaining references just in case
echo "🔎 Final scan for any remaining 'loveable' references:"
grep -ril "loveable" src || echo "✅ No remaining references found in src/"

echo "✅ Cleanup complete!"
